### ISSUE TITLE
namespace redefinition problem

### ISSUE THREAD

**Issue by Xeverous** [cycfi/infra#1]
https://github.com/cycfi/infra/blob/991d014e166bbbf10eef88d0a319abcc95fadf67/include/infra/filesystem.hpp#L23-L29

I expected it is going to happen at some point... My project uses `fs` namespace consistently for its code. Can you change this? IMO such short namespace definition is rather risky at global scope. Maybe use `cycfi::fs` or `infra::fs`?

**Comment by djowel** [comment]
Good point. Feel free to place that in the cycfi namespace. PR would be great!

**Comment by Xeverous** [comment]
#2

**Comment by djowel** [comment]
merged. thanks!

**Comment by Xeverous** [comment]
This was actually a mistake, because the change also enclosed entire included libraries. Fixed in #3
