### ISSUE TITLE
Requires BOOST - asio.hpp

### ISSUE THREAD

**Issue by wsberry** [cycfi/infra#10]
Building on a newly cloned elements (and infra) it appears that BOOST is still required:

See: \elements\lib\include\elements/view.hpp
Line: 17

My understanding was that BOOST should no longer be required.

System Overview:
Windows 10 Build w/Visual Studio 19

**Comment by wsberry** [comment]
Installed header only asio library (see: https://github.com/chriskohlhoff/asio.git)
Additional Information here:
http://think-async.com/Asio/AsioAndBoostAsio.html
Build succeeded. Ran both 'BasicSlidersAndKnobs' and 'Dialogs' projects successfully. 

Also, thankyou for the great work!

**Comment by djowel** [comment]
> Installed header only asio library (see: https://github.com/chriskohlhoff/asio.git)
> Additional Information here:
> http://think-async.com/Asio/AsioAndBoostAsio.html
> Build succeeded. Ran both 'BasicSlidersAndKnobs' and 'Dialogs' projects successfully.
> 
> Also, thankyou for the great work!

Elements should have installed that as a submodule already, No?

https://github.com/cycfi/elements/tree/master/lib/external

**Comment by wsberry** [comment]
hmmm...../repos/elements/lib/external/asio was empty. I did not clone with
'--recursive'. Should I have?

Thanks

Bill Berry

**Comment by djowel** [comment]
> hmmm...../repos/elements/lib/external/asio was empty. I did not clone with '--recursive'. Should I have?

Yes. Here's what's in the setup docs...

```
git clone --recurse-submodules  https://github.com/cycfi/elements.git
```

**Comment by wsberry** [comment]
I apologize for not reading them through more carefully.

Thanks for the update,

Bill Berry

**Comment by djowel** [comment]
> I apologize for not reading them through more carefully.

Oh not a problem at all :-)
