### ISSUE TITLE
to_string off-by-one bug

### ISSUE THREAD

**Issue by Xeverous** [cycfi/infra#11]
https://github.com/cycfi/infra/blob/4636dd500010604888cb057222817e301a0035ff/include/infra/support.hpp#L344-L350

Character literals also include terminating null byte, so for `u8""` this function would use `N = 1` which is wrong. It should use `N -1`. There is no way to have a literal character array of length 0.

**Comment by djowel** [comment]
Can you point out where this is being used with a literal string? This code is probably outdated and should be removed.

This is not really a bug. The input is not necessarily from literals. `char8_t s[3] = { 'x', 'y', 'z' };`  for example is valid input. But yes, it can be error prone. For that matter, your solution is incorrect. The correct solution is to have an overload for `std::string to_string(char8_t const* s);` if indeed there's a case where this is used with a literal string.

**Comment by Xeverous** [comment]
I have only analyzed use case with string literals - if someone uses an array of character literals then it indeed will be a different usecase.

Within elements, there are no uses of this function template.

**Comment by djowel** [comment]
Deleted
