### ISSUE TITLE
filesystem linking

### ISSUE THREAD

**Issue by Xeverous** [cycfi/infra#4]
There is a problem with GCC and Clang in certain range of versions because while they have `std::filesystem` implementation they require explicit linking to it because at that point the library was not merged into the core standard library implementation.

https://stackoverflow.com/questions/53807011/undefined-reference-error-with-new-filesystem-library-and-clang7
https://stackoverflow.com/questions/58545562/what-is-the-correct-way-to-link-c17-filesystem-with-cmake

There is no consensus in CMake too: https://gitlab.kitware.com/cmake/cmake/issues/17834

I have this problem on one machine and I think the cleanest thing we can do is to give explicit CMake options to add `-lc++fs` or `-lstdc++fs` flags to infra target.

**Comment by djowel** [comment]
That is why in certain versions of Apple clang, I use ghc::filesystem.

**Comment by Xeverous** [comment]
#6 is merged, closing
